[workspace]
members = [
    "contracts/airdrop", 
     "contracts/lp_bootstrap_auction", 
     "contracts/lockdrop", 
     "contracts/mocks/mock_terraswap/*", 
    "packages/*"
]


[profile.release.package.astroport]
opt-level = 3
debug = false
debug-assertions = false
codegen-units = 1
incremental = false


[profile.release.package.astroport-periphery]
opt-level = 3
debug = false
debug-assertions = false
codegen-units = 1
incremental = false


[profile.release]
rpath = false
lto = true
overflow-checks = true
